spring:
  config:
    import: "optional:classpath:env.properties"
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE

openai:
  secret: ${OPENAI_API_KEY}

email:
  mailgun:
    domain: mg.tarik-maljanovic.tech
    from-email: taskit@tarik-maljanovic.tech
    username: api
    password: ${MAILGUN_API_KEY}
    frontend-url: https//localhost:3000/
    frontend-reset-password-url: https://localhost:3000/
